name: Publicar en NPM

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'README.md'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Instalar pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Obtener dependencias
        run: pnpm install

      - name: Construir paquetes
        run: pnpm run build

      - name: Ejecutar pruebas
        run: pnpm test

      - name: Publicar paquetes
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          pnpm -r publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}